import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import artContext from "../functions/experienceArtContext.js";
const progressSource=(await readFile(new URL("../functions/journeyProgress.js",import.meta.url),"utf8")).replace('module.exports=', 'const journeyProgress=');
const source=(await readFile(new URL("../lib/experienceVisuals.js",import.meta.url),"utf8")).replace('import artContext from "../functions/experienceArtContext";',`const artContext={experienceArtContext:${artContext.experienceArtContext.toString()}};`).replace('import journeyProgress from "../functions/journeyProgress";',progressSource);
const {getExperienceTheme,buildMemoryChapters,journeyFinished,missionMapUrl}=await import("data:text/javascript;base64,"+Buffer.from(source).toString("base64"));
const flow=[{id:"a",title:"Photo",type:"photo"},{id:"b",title:"Note",type:"note"}];
assert.equal(getExperienceTheme({location:"פוקט, תאילנד"}).key,"thailand");
assert.equal(getExperienceTheme({location:"Athens, Greece"}).key,"greece");
assert.equal(getExperienceTheme({location:"ירושלים"}).key,"israel");
assert.equal(getExperienceTheme({location:"Japan"}).key,"journey");
assert.equal(getExperienceTheme({type:"יום הולדת"}).key,"celebration");
assert.equal(getExperienceTheme({location:"Greece",visualTheme:"nature"}).key,"nature");
assert.equal(journeyFinished({currentMissionIndex:0},[]),false);
assert.equal(journeyFinished({completedMissionIds:["a"]},flow),false);
assert.equal(journeyFinished({completedMissionIds:["b","a"]},flow),true);
assert.equal(journeyFinished({currentMissionIndex:2},flow),true);
const photos=Array.from({length:11},(_,i)=>({id:"p"+i,missionId:"a"}));
const answers=Array.from({length:5},(_,i)=>({id:"q"+i,missionId:"a",text:"answer"}));
const pages=buildMemoryChapters(flow,photos,answers,[{completedMissionIds:["a","b"]}]);
assert.equal(pages.length,4);
assert.equal(pages.flatMap(p=>p.photos).length,11);
assert.equal(pages.flatMap(p=>p.quotes).length,5);
assert.equal(pages.at(-1).mission.id,"b");
assert.equal(buildMemoryChapters([], [{id:"orphan",missionId:"deleted"}],[])[0].photos[0].id,"orphan");
assert.deepEqual(buildMemoryChapters(flow,[],[],[]),[]);
assert.equal(missionMapUrl({lat:0,lng:0}),"https://www.google.com/maps/search/?api=1&query=0%2C0");
assert.equal(missionMapUrl({lat:"",lng:""}),null);
assert.equal(missionMapUrl({lat:100,lng:10}),null);
assert.equal(missionMapUrl({text:"Thailand"}),null);
assert.ok(missionMapUrl({location:"Bangkok"}).endsWith("Bangkok"));
console.log("20 route, completion and album pagination checks passed");
