import assert from 'node:assert/strict';
import fs from 'node:fs';
const {guidanceState,participantHint}=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(new URL('../lib/experienceGuidance.js',import.meta.url),'utf8')).toString('base64'));
assert.equal(guidanceState({}).needsSelection,true);
assert.equal(guidanceState({id:'draft',flow:[{id:'a'}]}).published,false);
assert.equal(guidanceState({id:'live',status:'live',joinCode:'CODE'}).published,true);
assert.equal(guidanceState({id:'broken',status:'live'}).published,false);
assert.equal(guidanceState({id:'paused',status:'live',joinCode:'CODE',paused:true}).paused,true);
assert.match(participantHint({type:'story',isLocationPoll:true,organizerDecides:true},'he'),/ההצבעה נשמרת/);
assert.match(participantHint({type:'branch',organizerDecides:true},'he'),/מחכים לבחירת המארגן/);
assert.match(participantHint({type:'quiz'},'he'),/נבדקת מיד/);
assert.match(participantHint({type:'map',lat:32,lng:35},'he'),/בדיקת המיקום/);
assert.doesNotMatch(participantHint({type:'map',lat:32},'he'),/בדיקת המיקום/);
console.log('Guidance states and participant instructions match the actual workflow.');
