const assert=require('node:assert/strict');
const {normalizeProgress,reorderProgress,advanceProgress,currentMissionIndex}=require('../functions/journeyProgress');
const flow=Array.from({length:6},(_,i)=>({id:'m'+(i+1),title:'Stop '+(i+1),points:100}));
const swapped=[flow[0],flow[1],flow[2],flow[5],flow[4],flow[3]];
const legacy={completedMissionIds:['m1','m2'],currentMissionIndex:3,points:200};
const migrated=reorderProgress(legacy,flow,swapped);
assert.equal(migrated.currentMissionId,'m4');assert.equal(currentMissionIndex(migrated,swapped),5);
assert.deepEqual(migrated.completedMissionIds,['m1','m2']);assert.deepEqual(migrated.skippedMissionIds,['m3']);assert.equal(migrated.points,200);
const next=advanceProgress(migrated,swapped,'m4');assert.equal(next.currentMissionId,'m6');assert.equal(next.points,300);
assert.ok(!next.completedMissionIds.includes('m6'));assert.equal(next.currentMissionIndex,3);
const duplicate=advanceProgress(next,swapped,'m4');assert.equal(duplicate.points,300);assert.equal(duplicate.currentMissionId,'m6');
assert.throws(()=>advanceProgress(next,swapped,'m5'),/active mission changed/);
const final=advanceProgress(advanceProgress(next,swapped,'m6'),swapped,'m5');assert.equal(final.journeyEnded,true);assert.equal(final.points,500);
assert.equal(reorderProgress(final,swapped,flow).journeyEnded,true);
const skipped=advanceProgress(normalizeProgress({},flow),flow,'m1',{skip:true});assert.equal(skipped.points,0);assert.deepEqual(skipped.completedMissionIds,[]);assert.deepEqual(skipped.skippedMissionIds,['m1']);
const branch=advanceProgress({},flow,'m1',{branchTarget:'m4'});assert.deepEqual(branch.skippedMissionIds,['m2','m3']);assert.equal(branch.currentMissionId,'m4');
const branchEnd=advanceProgress(branch,flow,'m4',{branchTarget:null});assert.equal(branchEnd.journeyEnded,true);assert.deepEqual(branchEnd.completedMissionIds,['m1','m4']);
assert.equal(normalizeProgress({},[]).journeyEnded,false);
assert.equal(normalizeProgress({completedMissionIds:flow.map(m=>m.id)},flow).journeyEnded,true);
assert.equal(advanceProgress({},[{id:'zero',points:0}],'zero').points,0);
assert.equal(advanceProgress({},flow,'m1',{awardedPoints:81}).points,81);
assert.equal(advanceProgress({},flow,'m1',{awardedPoints:900}).points,100);
console.log('25 progress migration, live swap, skipped/branch and duplicate-completion checks passed');
