"use client";
import {Fragment,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {generateExperienceArtworkRemote,uploadCelebrationPortrait,updateExperienceRemote,generateCelebrationCartoonRemote} from "../lib/morivoData";
import {firebaseConfigured} from "../lib/firebase";
import artContext from "../functions/experienceArtContext";
import {getExperienceTheme,VISUAL_THEMES,missionDone,missionActive,journeyFinished} from "../lib/experienceVisuals";
import {buildRouteGroups,dayRangeText} from "../lib/routeGroups";
import RouteMissionPanel from "./RouteMissionPanel";
import DestinationBackdrop from "./DestinationBackdrop";
import LinkifiedText from "./LinkifiedText";
const icons={photo:"📸",video:"🎬",map:"🗺️",quiz:"✅",puzzle:"🧩",note:"✍️",story:"📖",reward:"🏆"};
export default function ExperienceRoute({experience,people=[],media=[],answers=[],onMemory,onStudio,onTheme,onSwap,onSaveMission,lang}){
 const he=lang==="he",flow=experience.flow||[],theme=getExperienceTheme(experience);
 const [selected,setSelected]=useState(experience.flow?.[0]?.id||null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[popupMission,setPopupMission]=useState(null);
 useEffect(()=>{if(!flow.some(m=>m.id===selected))setSelected(flow[0]?.id||null)},[flow,selected]);
 const [artStatus,setArtStatus]=useState("idle"),[artError,setArtError]=useState("");
 const [reordering,setReordering]=useState(false),[dragging,setDragging]=useState(null),[dirty,setDirty]=useState(false),[orderNotice,setOrderNotice]=useState("");
 function selectMission(id){if(id===selected)return;if(dirty&&!window.confirm(he?"לעבור לתחנה אחרת ולוותר על השינויים שלא נשמרו?":"Discard unsaved changes and open another stop?"))return;setDirty(false);setSelected(id)}
 async function swap(a,b){if(!onSwap||a===b||reordering)return;setReordering(true);setError("");try{await onSwap(a,b);setOrderNotice(he?"סדר התחנות נשמר. ההתקדמות נשארה משויכת למשימות.":"Stop order saved. Progress stays linked to each mission.")}catch(e){setError(e.message);throw e}finally{setReordering(false);setDragging(null)}}
 const attempted=useRef("");
 const context=artContext.experienceArtContext(experience),automatic=!experience.visualTheme||experience.visualTheme==="auto";
 const artReady=experience.routeArtwork?.context===context&&experience.routeArtwork?.url;
 const canGenerate=!!onTheme&&firebaseConfigured&&experience.id&&!experience.id.startsWith("local-")&&experience.id!=="thailand-demo";
 async function generateBackground(){setArtStatus("loading");setArtError("");try{await generateExperienceArtworkRemote(experience.id);setArtStatus("ready")}catch(e){setArtStatus("error");setArtError(he?"לא הצלחנו ליצור את הרקע כרגע. מוצגת בינתיים תמונת הסגנון; אפשר לנסות שוב.":"Background creation failed. Showing the style image for now; you can retry.")}}
 const [cartoonStatus,setCartoonStatus]=useState("idle");
 async function generateCartoon(){setCartoonStatus("loading");setError("");try{await generateCelebrationCartoonRemote(experience.id);setCartoonStatus("idle")}catch(e){setCartoonStatus("error");setError(e.message)}}
 useEffect(()=>{const key=experience.id+context;if(automatic&&canGenerate&&!artReady&&(experience.name||experience.location)&&attempted.current!==key){attempted.current=key;generateBackground()}},[automatic,canGenerate,context,artReady,experience.id]);
 const index=Math.max(0,flow.findIndex(m=>m.id===selected)),mission=flow[index];
 const finished=people.filter(p=>!p.pending&&journeyFinished(p,flow)).length;
 const groups=buildRouteGroups(experience,flow,he);
 const nextIndex=flow.findIndex((m,i)=>people.some(p=>!p.pending&&missionActive(p,m,flow)));
 const cartoonBg=theme.key==="celebration"&&experience.celebrationPortrait?.useAsBackground&&experience.celebrationPortrait?.cartoonUrl;
 const mapBackdrop=cartoonBg||(/(תאילנד|thailand|פוקט|phuket)/i.test(String(`${experience.name||""} ${experience.location||""} ${experience.story||""}`))?"/route-thailand.svg":"/route-journey.svg");
 return <section className="experienceRoute" style={{"--route-accent":theme.accent}}>
  <div className="routeHeading"><div><span className="routeEyebrow">{he?"המסלול שלכם":"YOUR EXPERIENCE ROUTE"}</span><h3>{experience.location||experience.name||(he?"כל מסע מתחיל ברגע אחד":"Every journey starts with a moment")}</h3><p>{he?"תרשים התקדמות לפי סדר המשימות · אינו מפת ניווט":"Progress along your missions · schematic, not a navigation map"}</p></div>
   {onTheme&&<label className="routeThemePicker">{he?"סגנון המסלול":"Route style"}<select value={experience.visualTheme||"auto"} disabled={saving} onChange={async e=>{setSaving(true);setError("");try{await onTheme(e.target.value)}catch(e){setError(e.message)}finally{setSaving(false)}}}><option value="auto">{he?"התאמה אוטומטית ליעד":"Automatic by destination"}</option>{Object.entries(VISUAL_THEMES).map(([key,x])=><option key={key} value={key}>{he?x.he:x.en}</option>)}</select></label>}
  </div>
  {error&&<p role="alert">{error}</p>}
  {onSwap&&flow.length>1&&<div className="routeReorderHint"><span>{he?"גררו תחנה על תחנה אחרת כדי להחליף ביניהן, או בחרו החלפת מיקום בחלונית התחנה. במקלדת: Alt + חץ למעלה/למטה.":"Drag one stop onto another to swap, or use the stop panel. Keyboard: Alt + Up/Down."}</span><span role="status">{reordering?(he?"שומרים את הסדר…":"Saving order…"):orderNotice}</span></div>}
  {automatic&&<div className="routeArtStatus" role="status">{artReady?(he?"רקע AI אישי לפי שם החוויה והמיקום · איור להמחשה":"Personal AI background based on your experience · illustration"):artStatus==="loading"?(he?"יוצרים את הרקע האישי שלכם… בינתיים מוצגת תמונת הסגנון.":"Creating your personal background… showing the style image meanwhile."):artError||(!canGenerate?(he?"הרקע האישי ייווצר אחרי שמירת החוויה בידי המארגן.":"Your personal background will be created after the organizer saves the experience."):"")}{artStatus==="error"&&canGenerate&&<button type="button" onClick={generateBackground}>{he?"ניסיון נוסף":"Retry"}</button>}</div>}
  {theme.key==="celebration"&&onTheme&&<div className="routePortraitUpload"><label>{he?"שילוב תמונת ילד/ת יום ההולדת":"Add the birthday child's photo"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!canGenerate||saving} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setSaving(true);setError("");try{await uploadCelebrationPortrait(experience.id,file)}catch(e){setError(e.message)}finally{setSaving(false)}}}/></label><small>{he?"תמונה לבחירתכם במסגרת חגיגית, ללא שינוי הפנים. השתמשו בתמונה שיש לכם רשות להציג.":"Your chosen photo in a festive frame, without changing the face. Use a photo you have permission to show."}</small>{experience.celebrationPortrait?.url&&<button type="button" disabled={saving} onClick={async()=>{setSaving(true);try{await updateExperienceRemote(experience.id,{celebrationPortrait:null})}catch(e){setError(e.message)}finally{setSaving(false)}}}>{he?"הסרת התמונה מהעיצוב":"Remove photo from design"}</button>}
   {experience.celebrationPortrait?.url&&<div className="celebrationCartoonBox">
    <button type="button" disabled={!canGenerate||cartoonStatus==="loading"} onClick={generateCartoon}>{cartoonStatus==="loading"?(he?"יוצרים קריקטורה…":"Creating cartoon…"):(he?"יצירת גרסת קריקטורה מהתמונה":"Generate a cartoon version")}</button>
    {cartoonStatus==="error"&&<small>{he?"יצירת הקריקטורה נכשלה. אפשר לנסות שוב.":"Cartoon creation failed. You can try again."}</small>}
    {experience.celebrationPortrait?.cartoonUrl&&<div className="celebrationCartoonPreview">
     <img src={experience.celebrationPortrait.cartoonUrl} alt={he?"תצוגה מקדימה של הקריקטורה":"Cartoon preview"}/>
     <button type="button" onClick={async()=>{setSaving(true);setError("");try{await updateExperienceRemote(experience.id,{"celebrationPortrait.useAsBackground":!experience.celebrationPortrait?.useAsBackground})}catch(e){setError(e.message)}finally{setSaving(false)}}}>{experience.celebrationPortrait?.useAsBackground?(he?"הפסקת השימוש כרקע המשימות":"Stop using as missions background"):(he?"שימוש כרקע המשימות":"Use as missions background")}</button>
    </div>}
   </div>}</div>}
  {flow.length?<div className="routeLayout">
   <div className="routeJourneyMap" style={cartoonBg?{backgroundImage:`linear-gradient(rgba(255,255,255,.84),rgba(255,255,255,.84)),url(${mapBackdrop})`,backgroundSize:"cover",backgroundPosition:"center",backgroundRepeat:"no-repeat"}:{backgroundImage:`url(${mapBackdrop})`}} aria-label={he?"מפת המסע לפי ימים ויעדים":"Journey map by days and destinations"}>
    <div className="routeMapLegend"><span><i className="legendDone">✓</i>{he?"הושלם":"Completed"}</span><span><i className="legendCurrent">●</i>{he?"מתבצע עכשיו":"In progress"}</span><span><i className="legendNext">→</i>{he?"המשימה הבאה":"Next"}</span></div>
    {groups.map(g=><section className="routeDayGroup" key={g.key}><header><span className="routeDayBadge">{g.label}</span>{dayRangeText(g.missions,he)&&<small>{dayRangeText(g.missions,he)}</small>}</header><div className="routeMissionCircles">{g.missions.map(({m,i},stopIndex)=><Fragment key={m.id}><button className={"routeMissionCircle "+(people.length>0&&people.every(p=>p.pending||missionDone(p,m,i)?true:false)?"isDone ":"")+(people.some(p=>!p.pending&&missionActive(p,m,flow))?"isCurrent ":"")+(!people.some(p=>!p.pending&&missionActive(p,m,flow))&&i===nextIndex?"isNext ":"")} onClick={()=>setPopupMission(m)} aria-pressed={i===index} title={m.title}><span className="circleNumber">{people.length>0&&people.every(p=>p.pending||missionDone(p,m,i))?"✓":i+1}</span><span className="circleIcon">{icons[m.type]||theme.motif}</span><b>{m.title}</b><small>{people.length>0&&people.every(p=>p.pending||missionDone(p,m,i))?(he?"הושלם":"Done"):people.some(p=>!p.pending&&missionActive(p,m,flow))?(he?"עכשיו":"Now"):i===nextIndex?(he?"הבא":"Next"):(he?"ממתינה":"Upcoming")}</small></button></Fragment>)}</div></section>)}
   </div>
   <div className="routeDetail">
    <RouteMissionPanel key={mission.id} mission={mission} index={index} flow={flow} people={people} media={media} answers={answers} onSave={onSaveMission} onSwap={onSwap?swap:undefined} onDirtyChange={setDirty} lang={lang}/>
    <button className="routeBookButton" onClick={onMemory}>{he?"פתיחת ספר הזיכרונות":"Open memory book"}</button>
    <small>{finished?he?finished+" משתתפים סיימו את המסע":finished+" participants finished":he?"הספר נאסף אוטומטית לאורך החוויה":"Your book is collected automatically throughout the experience"}</small>
   </div>
  </div>:<div className="routeEmpty"><DestinationBackdrop theme={theme}/><div><h3>{he?"המסלול שלכם עוד רגע מתחיל":"Your route is about to begin"}</h3><p>{he?"הוסיפו משימות לחוויה כדי לראות כאן תחנות, משתתפים וזיכרונות.":"Add missions to see your stops, participants and memories here."}</p><button onClick={onStudio}>{he?"בניית המסלול בסטודיו":"Build your route in Studio"}</button></div></div>}
 <style jsx global>{`  .experienceRoute .routeJourneyMap{position:relative;overflow:hidden;background-color:#12172a;background-position:center;background-size:cover;background-repeat:no-repeat;border:1px solid rgba(255,255,255,.1);border-radius:30px;box-shadow:0 18px 45px rgba(0,0,0,.3)} .experienceRoute .routeJourneyMap:before{content:"";position:absolute;inset:0;background:linear-gradient(rgba(10,14,26,.72),rgba(10,14,26,.72)),radial-gradient(circle at 15% 18%,rgba(139,92,246,.18),transparent 24%),radial-gradient(circle at 86% 80%,rgba(95,208,232,.14),transparent 28%);pointer-events:none} .experienceRoute .routeDayGroup{position:relative;z-index:1;padding:18px 0 25px}.experienceRoute .routeDayGroup+.routeDayGroup{border-top:1px dashed rgba(255,255,255,.12)}.experienceRoute .routeMissionCircles{display:grid;grid-template-columns:repeat(4,minmax(92px,1fr));gap:10px}.experienceRoute .routeMissionCircle{width:100%;min-height:108px;padding:8px 5px;font-size:11px;border-radius:22px;background:rgba(18,23,41,.93);border:2px solid rgba(255,255,255,.12);box-shadow:0 8px 18px rgba(0,0,0,.25);color:#e5e7f0}.experienceRoute .routeMissionCircle.isDone{background:rgba(89,211,154,.14);border-color:#59d39a}.experienceRoute .routeMissionCircle.isCurrent{background:rgba(245,169,78,.14);border-color:#f5a94e;box-shadow:0 0 0 4px rgba(245,169,78,.2)}.experienceRoute .routeMissionCircle.isNext{background:rgba(95,208,232,.12);border-color:#5fd0e8}.experienceRoute .routeConnector{display:none}.routeMissionPopupOverlay{position:fixed;inset:0;z-index:1300;background:rgba(10,14,26,.6);display:flex;align-items:center;justify-content:center;padding:20px;overflow-y:auto}.routeMissionPopupCard{position:relative;width:min(420px,100%);max-height:88vh;overflow-y:auto;background:#121729;color:#f3f4f9;border-radius:24px;padding:30px 24px 24px;box-shadow:0 25px 70px rgba(0,0,0,.4);border:1px solid rgba(255,255,255,.1);text-align:center}.routeMissionPopupClose{position:absolute;top:12px;inset-inline-end:14px;border:0;background:transparent;font-size:25px;color:#8b93a8;cursor:pointer;line-height:1}.routeMissionPopupNumber{width:38px;height:38px;margin:auto;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#8b5cf6,#6d4fd8);color:#fff;font-weight:800}.routeMissionPopupIcon{font-size:30px;margin:8px}.routeMissionPopupCard h4{margin:8px 0;font-size:20px}.routeMissionPopupCard>p{font-size:13px;line-height:1.6;white-space:pre-wrap;color:#c3c9d9}.routeMissionPopupFull{margin-top:14px;text-align:start}.routeMissionPopupFull .routeMissionEditor{max-height:none}@media(max-width:700px){.experienceRoute .routeMissionCircles{grid-template-columns:repeat(2,minmax(110px,1fr))}.experienceRoute .routeMissionCircle:nth-of-type(4n):after{display:block}.experienceRoute .routeMissionCircle:nth-of-type(2n):after{display:none}} `}</style>
 {popupMission&&typeof document!=="undefined"&&createPortal(<div className="routeMissionPopupOverlay" role="presentation" onClick={()=>setPopupMission(null)}><div className="routeMissionPopupCard" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button type="button" className="routeMissionPopupClose" onClick={()=>setPopupMission(null)} aria-label={he?"סגירה":"Close"}>×</button><div className="routeMissionPopupNumber">{flow.findIndex(x=>x.id===popupMission.id)+1}</div><div className="routeMissionPopupIcon">{icons[popupMission.type]||theme.motif}</div><h4>{popupMission.title}</h4><p>{popupMission.text||popupMission.description||""}</p><div className="routeMissionPopupFull"><RouteMissionPanel key={popupMission.id} mission={popupMission} index={flow.findIndex(x=>x.id===popupMission.id)} flow={flow} people={people} media={media} answers={answers} onSave={onSaveMission} onSwap={onSwap?swap:undefined} onDirtyChange={setDirty} lang={lang}/></div></div></div>,document.body)} </section>;
}
