"use client";
import {useEffect,useState} from "react";
export default function ExperienceShare({experience,lang,setView,afterPublish=false}){
 const he=lang==="he",[url,setUrl]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{setMessage("");setUrl(experience.joinCode?`${window.location.origin}${window.location.pathname}?join=${encodeURIComponent(experience.joinCode)}`:"")},[experience.id,experience.joinCode]);
 if(experience.status!=="live"||!experience.joinCode)return null;
 async function copy(){try{await navigator.clipboard.writeText(url);setMessage(he?"הקישור הועתק — אפשר להדביק ב־WhatsApp או בהודעה למשתתפים.":"Link copied — paste it into WhatsApp or a message to participants.")}catch{setMessage(he?"אפשר לסמן ולהעתיק את הקישור מהשדה שמתחת.":"Select and copy the link from the field below.")}}
 return <section className="experienceShare" id="experience-share" tabIndex={-1} aria-label={he?"הזמנת משתתפים":"Invite participants"}><div><span className="guidanceEyebrow">{afterPublish?(he?"החוויה פורסמה":"EXPERIENCE PUBLISHED"):(he?"מזמינים משתתפים":"INVITE PARTICIPANTS")}</span><h3>{he?"הצעד הבא: שולחים את הקישור":"Next: share the join link"}</h3><p>{he?"המשתתפים פותחים את הקישור, מזינים שם ומצטרפים. כשהם ייכנסו, תוכלו לראות אותם בניהול החי.":"Participants open this link, enter their name and join. They appear in live management after joining."}</p></div><div className="shareLinkRow"><label>{he?"קישור הצטרפות":"Join link"}<input readOnly dir="ltr" value={url} onFocus={e=>e.target.select()}/></label><button onClick={copy} disabled={!url}>{he?"העתקת קישור":"Copy link"}</button></div><div className="shareNextActions"><span>{he?"קוד להצטרפות ידנית":"Manual join code"}: <strong dir="ltr">{experience.joinCode}</strong></span>{url&&<a href={url} target="_blank" rel="noopener noreferrer">{he?"פתיחת מסך ההצטרפות ↗":"Open join screen ↗"}</a>}{afterPublish&&<button onClick={()=>setView("runtime")}>{he?"מעבר לניהול חי":"Go to live management"}</button>}</div><p role="status" className="shareFeedback">{message}</p></section>;
}
