"use client";
import {useEffect,useMemo,useState} from "react";
import { firebaseConfigured } from "../lib/firebase";
import { completeMissionRemote, joinExperienceByCode, subscribeExperience } from "../lib/morivoData";
import { uploadMissionPhoto } from "../lib/mediaData";

export default function Participant({experience,setExperience,setView,setActiveId}){
 const [code,setCode]=useState(experience.joinCode||""); const [name,setName]=useState("Guest"); const [joined,setJoined]=useState(false); const [done,setDone]=useState(false); const [file,setFile]=useState(null); const [preview,setPreview]=useState(""); const [uploading,setUploading]=useState(false); const [progress,setProgress]=useState(0); const [joinedExperienceId,setJoinedExperienceId]=useState(experience.id);
 useEffect(()=>{if(!file){setPreview("");return;} const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u)},[file]);
 useEffect(()=>{if(!firebaseConfigured||!joinedExperienceId||joinedExperienceId==="thailand-demo")return;return subscribeExperience(joinedExperienceId,remote=>{if(remote)setExperience(remote)})},[joinedExperienceId]);
 const mission=useMemo(()=>experience.flow?.find(x=>x.type==="photo")||experience.flow?.[0],[experience]);
 async function join(){try{if(firebaseConfigured){const id=await joinExperienceByCode(code,name);setActiveId(id);setJoinedExperienceId(id)}setJoined(true)}catch(e){alert(e.message)}}
 async function uploadAndComplete(){if(!file&&firebaseConfigured){alert("Choose a photo first");return;}try{setUploading(true);if(firebaseConfigured){await uploadMissionPhoto({experienceId:joinedExperienceId||experience.id,mission,file,participantName:name,onProgress:setProgress});await completeMissionRemote(joinedExperienceId||experience.id,mission,name)}setDone(true)}catch(e){console.error(e);alert(e.message)}finally{setUploading(false)}}
 return <section className="panel narrow"><div className="tag">Participant Mode · Media Mission</div><h2>{joined?experience.name:"Join an experience."}</h2>{!joined?<><label>Your name</label><input value={name} onChange={e=>setName(e.target.value)}/><label>Join code</label><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><div className="actions centerActions"><button className="primary" onClick={join}>Join Experience</button></div></>:<div className="phone photoMissionPhone"><h3>{mission?.title}</h3><p>{mission?.text}</p>{!done&&<><label className="uploadBox"><span>{preview?"Change photo":"📸 Choose a photo"}</span><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{preview&&<img src={preview} alt="Mission preview" className="missionPreviewImage"/>}{uploading&&<div className="uploadProgress"><div style={{width:`${progress}%`}}></div><span>{progress}%</span></div>}</>}<div className="mission">{done?"✅ Photo saved · Mission completed":`Reward: ${mission?.reward||""}`}</div><button className="primary" onClick={uploadAndComplete} disabled={uploading||done}>{done?"Completed":uploading?"Uploading…":"Upload & Complete Mission"}</button></div>}<div className="actions centerActions"><button onClick={()=>setView("runtime")}>Runtime</button><button onClick={()=>setView("memory")}>Memory</button></div></section>
}
