"use client";
import {useState} from "react";
import {missionDone,missionActive,missionMapUrl} from "../lib/experienceVisuals";
import missionAnswers from "../functions/missionAnswers";
import LinkifiedText from "./LinkifiedText";
const typeNames={photo:["צילום","Photo"],video:["סרטון","Video"],map:["נקודת מיקום","Location"],quiz:["חידון בחירה","Multiple choice"],puzzle:["חידה","Riddle"],note:["שאלה פתוחה","Open question"],story:["סיפור","Story"],reward:["פרס","Reward"],branch:["בחירת מסלול","Branch"]};
export default function RouteMissionPanel({mission,index,flow,people,media,answers,onSave,onSwap,onDirtyChange,lang}) {
 const he=lang==="he",[tab,setTab]=useState("status"),[draft,setDraft]=useState(()=>missionAnswers.normalizeMission(mission)),[base,setBase]=useState(mission),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[swapTarget,setSwapTarget]=useState("");
 const completed=people.filter(p=>missionDone(p,mission,index)),active=people.filter(p=>missionActive(p,mission,flow)),skipped=people.filter(p=>!p.pending&&(p.skippedMissionIds||[]).includes(mission.id)),waiting=people.filter(p=>!completed.includes(p)&&!active.includes(p)&&!skipped.includes(p));
 const photos=media.filter(x=>x.missionId===mission.id),quotes=answers.filter(x=>x.missionId===mission.id),mapUrl=missionMapUrl(mission);
 const groups=[[he?"נמצאים בתחנה":"At this stop",active,"active"],[he?"השלימו":"Completed",completed,"done"],[he?"דולגו":"Skipped",skipped,"skipped"],[he?"טרם הגיעו":"Not here yet",waiting,"waiting"]];
 function patch(values){setDraft(d=>({...d,...values}));setDirty(true);onDirtyChange(true);setNotice("")}
 async function save(e){e.preventDefault();setError("");if(!draft.title.trim())return setError(he?"כתבו כותרת למשימה":"Add a mission title");if(draft.type==="quiz"&&(draft.options?.length<2||draft.options.some(x=>!x.trim()||/^[A-Dא-ד1-4]$/i.test(x.trim()))||new Set(draft.options).size!==draft.options.length||!draft.options.includes(draft.answer)))return setError(he?"הוסיפו לפחות שתי אפשרויות מילוליות שונות וסמנו תשובה נכונה.":"Add at least two distinct written choices and select the correct answer.");if(draft.type==="puzzle"&&!draft.answer?.trim())return setError(he?"הגדירו תשובה נכונה לחידה, או בחרו שאלה פתוחה.":"Set a riddle answer or choose an open question.");setBusy(true);try{await onSave(base,draft);setBase(draft);setDirty(false);onDirtyChange(false);setNotice(he?"המשימה נשמרה ומעודכנת אצל המשתתפים":"Saved and updated for participants");setTab("status")}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="routeMissionPanel">
  <div className="routeEyebrow">{he?"ניהול תחנה":"MANAGE STOP"} {index+1} / {flow.length}</div><h3>{mission.title}</h3>
  <div className="routePanelTabs" role="tablist" aria-label={he?"ניהול המשימה":"Mission management"}><button role="tab" aria-selected={tab==="status"} onClick={()=>setTab("status")}>{he?"משתתפים והתקדמות":"People & progress"}</button>{onSave&&<button role="tab" aria-selected={tab==="edit"} onClick={()=>{if(!dirty){setDraft(missionAnswers.normalizeMission(mission));setBase(mission)}setTab("edit")}}>{he?"עריכת המשימה":"Edit mission"}{dirty?" •":""}</button>}</div>
  {error&&<p role="alert" className="routePanelError">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {tab==="status"?<div role="tabpanel">
   <p className="routeDescription"><LinkifiedText text={mission.text||""}/></p>
   <div className="routeCounts"><span><b>{active.length}</b>{he?"כאן עכשיו":"Here now"}</span><span><b>{completed.length}</b>{he?"השלימו":"Completed"}</span><span><b>{photos.length+quotes.length}</b>{he?"תוצרים":"Submissions"}</span></div>
   {!people.length&&<p>{he?"עדיין לא הצטרפו משתתפים לחוויה.":"No participants have joined yet."}</p>}
   <div className="routeParticipantGroups">{groups.filter(g=>g[1].length).map(([title,rows,status])=><section key={status}><h4>{title} · {rows.length}</h4>{rows.map(p=><div className={"routeParticipantRow "+status} key={p.id||p.uid}><span className="routeStatusDot"/><strong>{p.name||p.participantName}</strong><small>{p.pending?(he?"טרם הצטרף":"Not joined"):`${photos.filter(x=>x.uid===(p.uid||p.id)).length+quotes.filter(x=>x.uid===(p.uid||p.id)).length} ${he?"תוצרים":"submissions"}`}</small></div>)}</section>)}</div>
   {mapUrl&&<a className="routeMapLink" href={mapUrl} target="_blank" rel="noopener noreferrer">{he?"פתיחת מיקום במפות ↗":"Open location in Maps ↗"}</a>}
   <div className="routeSubmissions"><h4>{he?"מה נשלח בתחנה":"Submissions at this stop"}</h4>{!photos.length&&!quotes.length&&<p>{he?"עדיין לא נשלחו תמונות או תשובות למשימה הזאת.":"No photos or answers for this mission yet."}</p>}{quotes.map(q=><blockquote key={q.id}><LinkifiedText text={q.text}/><cite>{q.participantName}</cite></blockquote>)}{photos.map(p=><figure key={p.id}>{p.contentType?.startsWith("video/")?<video controls preload="metadata" src={p.downloadURL}/>:<a href={p.downloadURL} target="_blank" rel="noopener noreferrer"><img src={p.downloadURL} alt={p.missionTitle||mission.title} loading="lazy"/></a>}<figcaption>{p.participantName}</figcaption></figure>)}</div>
  </div>:<form role="tabpanel" onSubmit={save} className="routeMissionEditor">
   <label>{he?"כותרת":"Title"}<input value={draft.title||""} maxLength={120} onChange={e=>patch({title:e.target.value})}/></label>
   <label>{he?"סוג המשימה":"Mission type"}<select value={draft.type} onChange={e=>patch({type:e.target.value,responseMode:e.target.value==="note"?"open":"graded",answer:"",options:e.target.value==="quiz"?["","",""]:e.target.value==="branch"?mission.options||[]:[]})}>{Object.entries(typeNames).filter(([key])=>key!=="branch"||mission.type==="branch").map(([key,label])=><option key={key} value={key}>{label[he?0:1]}</option>)}</select></label>
   <label>{he?"הנחיה למשתתף":"Participant instructions"}<textarea value={draft.text||""} maxLength={1400} rows={4} onChange={e=>patch({text:e.target.value})}/></label>
   {draft.type==="note"&&<small>{he?"כל תשובה אישית מתקבלת ונשמרת בספר.":"Every personal response is accepted and saved in the book."}</small>}
   {draft.type==="puzzle"&&<label>{he?"תשובה נכונה":"Correct answer"}<input value={draft.answer||""} maxLength={120} onChange={e=>patch({answer:e.target.value})}/></label>}
   {draft.type==="quiz"&&<fieldset><legend>{he?"אפשרויות — סמנו את הנכונה":"Choices — select the correct one"}</legend>{(draft.options||[]).map((option,i)=><div className="routeQuizOption" key={i}><input type="radio" name={"answer-"+mission.id} aria-label={(he?"תשובה נכונה ":"Correct choice ")+(i+1)} checked={!!option&&draft.answer===option} onChange={()=>patch({answer:option})}/><input aria-label={(he?"אפשרות ":"Choice ")+(i+1)} value={option} maxLength={120} onChange={e=>patch({options:draft.options.map((o,j)=>j===i?e.target.value:o),answer:draft.answer===option?e.target.value:draft.answer})}/><button type="button" aria-label={he?"הסרת אפשרות":"Remove choice"} onClick={()=>patch({options:draft.options.filter((_,j)=>j!==i),answer:draft.answer===option?"":draft.answer})}>×</button></div>)}{(draft.options||[]).length<6&&<button type="button" onClick={()=>patch({options:[...(draft.options||[]),""]})}>{he?"הוספת אפשרות":"Add choice"}</button>}</fieldset>}
   <label>{he?"מיקום התחנה":"Stop location"}<input value={draft.location||""} maxLength={200} onChange={e=>patch({location:e.target.value})}/></label>
   <label>{he?"נקודות":"Points"}<input type="number" min="0" max="500" value={draft.points??100} onChange={e=>patch({points:Math.max(0,Math.min(500,Number(e.target.value)||0))})}/></label>
   <label>{he?"תיאור הפרס":"Reward label"}<input value={draft.reward||""} maxLength={120} onChange={e=>patch({reward:e.target.value})}/></label>
   <div className="routeEditorActions"><button type="submit" className="primary" disabled={busy||!dirty}>{busy?(he?"שומר…":"Saving…"):(he?"שמירת המשימה":"Save mission")}</button><button type="button" disabled={busy} onClick={()=>{setDraft(missionAnswers.normalizeMission(mission));setBase(mission);setDirty(false);onDirtyChange(false);setError("");setTab("status")}}>{he?"ביטול":"Cancel"}</button></div>
  </form>}
  {onSwap&&flow.length>1&&<div className="routeSwapControls"><label>{he?"החלפת מיקום עם תחנה":"Swap position with stop"}<select value={swapTarget} disabled={busy} onChange={e=>setSwapTarget(e.target.value)}><option value="">{he?"בחרו תחנה":"Choose a stop"}</option>{flow.filter(m=>m.id!==mission.id).map(m=><option key={m.id} value={m.id}>{flow.indexOf(m)+1} · {m.title}</option>)}</select></label><button type="button" disabled={!swapTarget||busy} onClick={async()=>{setBusy(true);setError("");try{await onSwap(mission.id,swapTarget);setSwapTarget("");setNotice(he?"המיקומים הוחלפו; ההתקדמות נשמרה":"Positions swapped; progress preserved")}catch(e){setError(e.message)}finally{setBusy(false)}}}>{he?"החלפת מיקומים":"Swap positions"}</button></div>}
 </div>;
}
